from typing import List

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_async_db, get_current_user
from app.models.case import Case
from app.models.entity import Entity, EntityMergeProposal
from app.models.user import User
from app.schemas.entity import EntityMergeProposalResponse, EntityResponse

router = APIRouter(tags=["Entities"])


@router.get(
    "/cases/{case_id}/entities",
    response_model=List[EntityResponse],
    summary="List Case Entities",
)
async def list_case_entities(
    case_id: str,
    db: AsyncSession = Depends(get_async_db),
    current_user: User = Depends(get_current_user),
) -> List[EntityResponse]:
    stmt = select(Entity).where(Entity.case_id == case_id).order_by(Entity.created_at.desc())
    entities = (await db.execute(stmt)).scalars().all()
    return [EntityResponse.model_validate(e) for e in entities]


@router.get(
    "/cases/{case_id}/entities/candidates",
    response_model=List[EntityMergeProposalResponse],
    summary="Get Pending Entity Resolution Proposals",
    description="Retrieves pending entity merge proposals generated by similarity scoring without auto-merging.",
)
async def get_candidate_merge_proposals(
    case_id: str,
    db: AsyncSession = Depends(get_async_db),
    current_user: User = Depends(get_current_user),
) -> List[EntityMergeProposalResponse]:
    case_stmt = select(Case).where(Case.id == case_id)
    case_res = await db.execute(case_stmt)
    if not case_res.scalar_one_or_none():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Case with id '{case_id}' not found.",
        )

    stmt = (
        select(EntityMergeProposal)
        .where(EntityMergeProposal.case_id == case_id)
        .order_by(EntityMergeProposal.similarity_score.desc())
    )
    proposals = (await db.execute(stmt)).scalars().all()

    # Load entities for response
    results = []
    for p in proposals:
        src_e = (
            await db.execute(select(Entity).where(Entity.id == p.source_entity_id))
        ).scalar_one_or_none()
        tgt_e = (
            await db.execute(select(Entity).where(Entity.id == p.target_entity_id))
        ).scalar_one_or_none()

        if src_e and tgt_e:
            results.append(
                EntityMergeProposalResponse(
                    id=p.id,
                    case_id=p.case_id,
                    source_entity=EntityResponse.model_validate(src_e),
                    target_entity=EntityResponse.model_validate(tgt_e),
                    similarity_score=p.similarity_score,
                    reason=p.reason,
                    status=p.status,
                    created_at=p.created_at,
                )
            )

    return results
